package main

import (
	"net/http"

	"swagger-demo/handler"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	// docs is generated by Swag CLI, you have to import it.
	_ "github.com/swaggo/gin-swagger/example/basic/docs"
)

// @title Gin swagger
// @version 1.0
// @description Gin swagger 示例项目

// @contact.name wangk
// @contact.url https://wangk.top
// @contact.email wangkyx@qq.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
func main() {
	// 省略其他代码
	router := gin.Default()

	router.GET("/", func(context *gin.Context) {
		context.String(http.StatusOK, "hello gin")
	})

	url := ginSwagger.URL("http://localhost:8978/swagger/doc.json")
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))
	//router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	index := router.Group("/user")
	{
		// 添加 Get 请求路由
		index.GET("/user-save-by-query", handler.UserSaveByQuery)
		// 添加 Post 请求路由
		index.POST("/user-save", handler.UserSave)

	}

	router.Run(":8978")
}
